development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://doingnow-faye.herokuapp.com/faye"
  secret_token: "5f1aa52c506a0c3208d0c155fd83e48979792a4c85fcf979687f777ae57d56fb"
  signature_expiration: 86400 # one day
